### ISSUE TITLE
Update should be a PUT/UPDATE example.

### ISSUE THREAD

**Issue by allnash** [playframework/play-java-rest-api-example#28]
I see in the `conf/posts.routes` file that you are using a POST request to update the record. This is not a standard RESTful request. The request headers should be PUT or UPDATE.

Please update this example which is sort of abusing REST interpretability. 

Refer. https://en.wikipedia.org/wiki/Representational_state_transfer

**Comment by wsargent** [comment]
Please submit a pull request.

No Signature

**Comment by allnash** [comment]
Be glad to.

Should I fork it and create a local branch?

**Comment by dusanstanojeviccs** [comment]
I've created a Pull Request for this issue

https://github.com/playframework/play-java-rest-api-example/pull/33

**Comment by marcospereira** [comment]
Closed after #33.
