### ISSUE TITLE
Using a nosql approach for rest api

### ISSUE THREAD

**Issue by sharadm20** [playframework/play-java-rest-api-example#83]
If a tutorial for nosql would be provided that would be alot of help.

**Comment by cchantep** [comment]
Hi, please use the [forum/mailing list](https://discuss.lightbend.com/c/play) to discuss/ask question (this tracker is rather for actionable issue/feature request). Thx

**Comment by marcospereira** [comment]
Hey @sharadm20,

As @cchantep said, our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. Given that, I'm closing this.

Best.
